# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Amy Tai
description: > # this means to ignore newlines until "baseurl:"
  Personal website
  
  
baseurl: "/cards" # the subpath of your site, e.g. /blog
url: "http://amytai.ca" # the base hostname & protocol for your site

#sidebar
default-image: personal-picture.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 10
paginate_path: /page:num/

#social
facebook: https://www.facebook.com/amytai8
linkedin: https://www.linkedin.com/in/amy-tai/
github: https://github.com/catai9

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]

